Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -10,10 +10,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: step1
-        continue-on-error: true
         run: |
           echo "hello from step1"
-          exit 1
           sleep 10
       - name: my step2
         run: |
@@ -34,6 +32,7 @@ jobs:
   test: 
     runs-on: ubuntu-latest
     needs: [ build-a, build-b ]
+    if: ${{ always () }}
     steps:
       - name: step1
         run: |
@@ -55,6 +54,7 @@ jobs:
         run: |
           echo "hello from step2"
           sleep 10
+          
   notification-start: 
     runs-on: ubuntu-latest
     steps:
@@ -62,3 +62,12 @@ jobs:
         run: |
           echo "Job started"
           sleep 10
+  notification-failed:
+     runs-on: ubuntu-latest
+     needs: build-a
+     if: ${{ needs.build.result == 'failure' || failure() }}
+     steps:
+       - name: notify
+         run: |
+           echo "Build step got failed"
+           sleep 10
